try {
  const ret = await send(data)
} catch (err) {
  console.log(err)
}
